# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "ko-KR"
early_access: false

# 리뷰/채팅 톤을 고정한다
tone_instructions: >
  공식적이고 표준어를 사용하고, 문장 끝은 '다'로 마무리한다.
  칭찬은 최소화하고, 운영/장애/보안/성능/테스트 관점의 개선에 집중한다.
  지적은 반드시 '왜 문제인지(운영 관점) + 수정안 + 추가 테스트'를 포함한다.

reviews:
  # chill: 덜 잔소리, assertive: 더 촘촘한 피드백
  profile: "chill"

  # CodeRabbit이 자동으로 "changes requested"로 강하게 걸지 않도록 한다
  request_changes_workflow: false

  # PR 요약/워크스루 관련
  high_level_summary: true
  high_level_summary_instructions: >
    변경 목적, 핵심 변경점, 리스크/주의사항, 테스트/검증 방법 순서로 4~8줄 요약을 작성한다.
    추측이 필요한 부분은 단정하지 말고 확인 질문을 포함한다.
  review_status: true
  review_details: false

  # 교육용이므로 불필요한 장식은 끈다
  poem: false

  # 리뷰 대상 파일 범위( glob + '!패턴' 방식 )
  path_filters:
    - "src/**"
    - "build.gradle"
    - "build.gradle.kts"
    - "settings.gradle"
    - "settings.gradle.kts"
    - "!**/*.md"
    - "!**/*.adoc"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/*.lock"
    - "!**/generated/**"
    - "!**/build/**"
    - "!**/out/**"
    - "!**/.gradle/**"

  # 경로별 리뷰 가이드(스키마에 존재하는 path_instructions 사용)
  path_instructions:
    - path: "**/*.kt"
      instructions: >
        Kotlin 리뷰 기준이다.
        null-safety를 우선 확인하고, '!!' 사용은 불가피한 경우에만 허용한다.
        JPA 엔티티에 data class 사용 여부와 equals/hashCode 안정성을 점검한다.
        과도한 scope function으로 가독성이 떨어지면 더 명시적인 코드로 제안한다.
    - path: "**/*.java"
      instructions: >
        Java 리뷰 기준이다.
        Optional/Stream 남용으로 가독성이 떨어지면 단순화한다.
        예외 처리 시 cause를 보존하고, 사용자 메시지/로그 메시지를 분리하도록 제안한다.
    - path: "**/*Controller*.*"
      instructions: >
        Controller는 요청/응답 조립에 집중하고 비즈니스 로직은 Service로 이동한다.
        Bean Validation 적용 여부와 상태 코드/에러 응답 일관성을 점검한다.
    - path: "**/*Repository*.*"
      instructions: >
        JPA 쿼리 성능(N+1, fetch join/EntityGraph), 트랜잭션 경계, 인덱스/페이징 안전성을 점검한다.

  # 자동 리뷰 설정(문서 스키마: object)
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
    ignore_title_keywords:
      - "wip"
      - "draft"

chat:
  # PR에서 @coderabbitai 멘션 시 자동 응답
  auto_reply: true
